### ISSUE TITLE
Getting a  "could not find `lexer` in `__lalrpop_util`"

### ISSUE THREAD

**Issue by wags-1314** [lalrpop/lalrpop#650]
I have been following the LALRPOP tutorial and just tried implementing the parenthesized numbers example. But whenever I try to run, I get this error message:
```
bhargav@bhargav-kk:/mnt/c/bhargav/Programming/Language-stuff/brim$ cargo run
   Compiling libc v0.2.116
   ...
   Compiling lalrpop v0.19.7
   Compiling brim v0.1.0 (/mnt/c/bhargav/Programming/Language-stuff/brim)
error[E0432]: unresolved import `self::__lalrpop_util::lexer`
  --> /mnt/c/bhargav/Programming/Language-stuff/brim/target/debug/build/brim-9358516eba536307/out/grammar.rs:22:31
   |
22 |     use self::__lalrpop_util::lexer::Token;
   |                               ^^^^^ could not find `lexer` in `__lalrpop_util`

...
For more information about an error, try `rustc --explain E0432`.
error: could not compile `brim` due to 5 previous errors
```

This is my `main.rs`:
```rust
#[macro_use]
extern crate lalrpop_util;

lalrpop_mod!(pub grammar); // synthesized by LALRPOP

#[test]
fn calculator1() {
    assert!(grammar::TermParser::new().parse("22").is_ok());
    assert!(grammar::TermParser::new().parse("(22)").is_ok());
    assert!(grammar::TermParser::new().parse("((((22))))").is_ok());
    assert!(grammar::TermParser::new().parse("((22)").is_err());
}

fn main() {
    println!("Hello, world!");
}
```
This is my LALRPOP file:
```
use std::str::FromStr;

grammar;

pub Term: i32 = {
    <n:Num> => n,
    "(" <t:Term> ")" => t,
};

Num: i32 = <s:r"[0-9]+"> => i32::from_str(s).unwrap();
```
My `build.rs` which is outside the `src` folder:
```rust
extern crate lalrpop;

fn main() {
    lalrpop::process_root().unwrap();
}
```
And my `Cargo.toml`:
```toml
[package]
name = "brim"
version = "0.1.0"
edition = "2021"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lalrpop-util = "0.19.7"
regex = "1"

[build-dependencies]
lalrpop = { version = "0.19.7", features = ["lexer"] }
```
Any way to fix this?
